### ISSUE TITLE
Track data license with IAGA-2002 and ImagCDF formats.

### ISSUE THREAD

**Issue by jmfee-usgs** [INTERMAGNET/wg-www-gins-data-formats#1]
Proposal: add optional (but strongly recommended) "License" header to IAGA-2002 and ImagCDF headers.

The header value should be either
- (preferred) an identifier from the SPDX License List at https://spdx.org/licenses/
- or optionally a URL that resolves to the data license.

IAGA-2002 Example:
```
# License                CC-BY-NC-4.0                                 |
```

**Comment by CharlesBlais** [comment]
Should I add the license text to the INTERMAGNET FTP?

https://spdx.org/licenses/CC-BY-NC-4.0.html#licenseText

**Comment by SimonFlower** [comment]
We put some time into creating a license page for the INTERMAGNET web site:

https://intermagnet.github.io/data_conditions.html

Shouldn't the FTP license text reference this (as it also includes the list of institutes with license conditions that differ from CC-BY-NC 4.0)?

**Comment by CharlesBlais** [comment]
Are you suggesting that I put a conditions of use file under the FTP?  I can put one under the ftp://ftp.seismo.nrcan.gc.ca/intermagnet/ directory.  All I need is content.

> Unless otherwise noted, data downloaded through INTERMAGNET is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License. A list of institutes with different license conditions is given at the end of this page.
> 
> For more details, please visit https://intermagnet.github.io/data_conditions.html.

**Comment by SimonFlower** [comment]
I think that would work fine wouldn't it? Although it would be good for the new data conditions web page to be made public at more or less the same time, so that we're not communicating conflicting information about INTERMAGNET licenses.

**Comment by CharlesBlais** [comment]
Simon, is this doable at the BGS GIN since you alter the content?

**Comment by SimonFlower** [comment]
Yes, we could add that header in when creating data files from the GIN (all data files requested by users are created on the fly, as the data in the Edinburgh GIN is not held in any of the formats used for transporting data).

**Comment by CharlesBlais** [comment]
This highly depends on the way we move forward with transferring data.  If we opt for a message tranmission like MQTT or SeedLink, creation of IAGA2002 or CDF will be done at the end-point (BGS).  Should we put a hold on this discussion until more critical matters are addressed?

**Comment by SimonFlower** [comment]
I think that's realistic - putting this on hold for now.

**Comment by CharlesBlais** [comment]
I think we can close
