### ISSUE TITLE
Correcting non-IMO and former-IMO on the FTP

### ISSUE THREAD

**Issue by CharlesBlais** [INTERMAGNET/wg-www-gins-data-formats#4]
During the presentation of the agendas, Chris Turbitt indicated that some former-IMO and non-IMO are available on the INTERMAGNET FTP.  These include:

IMO | GIN
-- | --
ALE | Canada
DMC | Paris
EUA | Canada
LIV |  
KLI |  
MZL |  
QZH |  
SNK | Canada
TEO | Edinburgh
TST | Canada

I can confirm so far that the following were corrected EUA, SNK, and TST.  I will investigate for the others and update ticket.

**Comment by CharlesBlais** [comment]
Further investigation on the FTP and the rsync server led to these results

ALE = source Canada - will delete files after IMO was declared former
DMC = source Paris - sent invite to vmaury to INTERMAGNET GitHub - I will ask her if she can stop the transfer
EUA = removed
LIV = source Canada from GOES satellite transmission, stop in April 2019, will delete
KLI = unknown, russian observatory, stop in July 2018, will delete
MZL = source Edinburgh, stop in July 2012, will delete
QZH = source Edinburgh, stop in August 2014, will delete
SNK = removed
TEO = source Edinburgh  - will delete files after IMO was declared former
TST = removed

**Comment by CharlesBlais** [comment]
@ChrisTurbitt 

I am looking back this.  I've just deleted all that was safe to delete but DMC and TEO.  DMC still shows as active on the website so should it be closed and since when?  For TEO, when was it closed?

**Comment by ChrisTurbitt** [comment]
Hi @CharlesBlais 
TEO - withdrawn 9-Sep-2013
DMC - withdrawn 22-Aug-2016
Both of these have had IMO membership withdrawn so they should not be transmitting any more. If TEO was switched off at the EDI GIN 17-Apr-2018 I think.
KLI is not an IMO yet but has made an application. They are transmitting to PAR GIN as a test, so the data should not be mirrored to INTERMAGNET until they have been accepted. If you are contacting Virginie on DMC can you ask her about KLI too?

**Comment by CharlesBlais** [comment]
Thanks @ChrisTurbitt, I've corrected TEO and all others except for DMC

@vmaury-ipgp, would it be possible to stop the transmission of DMC variation data?

**Comment by CharlesBlais** [comment]
@ChrisTurbitt mentioned the below items

AMS    - designated as former IMO 19 April 2018
CZT     - designated as former IMO 13 August 2020
DMC    - designated as former IMO 22 April 2016
DRV    - designated as former IMO 13 August 2020

AMS received and DMC are still being received.  CZT and DRV I don't see them so @vmaury-ipgp, would those still transmit?

**Comment by vmaury-ipgp** [comment]
Hi Charles, 

I answered Chris, I just stopped transmissions.
Below are the latest transmission logs.

-- -- -- -- -- -- -- -- -- -- -- --
Fichier :ams20210322vmin.min 104 KB     23/03/2021      03:11:00 UTC+1
Fichier :czt20210309vmin.min 104 KB     10/03/2021      03:11:00 UTC+1
Fichier :dmc20210319vmin.min 104 KB     20/03/2021      03:11:00 UTC+1
Fichier :drv20210309vmin.min 104 KB     10/03/2021      03:41:00 UTC+1


Fichier :ams20210322vsec.sec 6078 KB    23/03/2021      03:11:00 UTC+1
Fichier :czt20210309vsec.sec 6078 KB    10/03/2021      03:11:00 UTC+1
Fichier :dmc20210319vsec.sec 6078 KB    20/03/2021      03:11:00 UTC+1
Fichier :drv20210309vsec.sec 6078 KB    10/03/2021      03:41:00 UTC+1
-- -- -- -- -- -- -- -- -- -- -- --
